# Preview me online:
# - https://editor.swagger.io/?url=https://raw.githubusercontent.com/EticaAI/urn-resolver/main/openapi.yml
# - https://editor-next.swagger.io/?url=https://raw.githubusercontent.com/EticaAI/urn-resolver/main/openapi.yml
openapi: 3.0.0
info:
  version: 1.0.0
  title: URN Resolver (very early draft)
  description: URN Resolver
paths:
  /:
    get:
      description: Index
      responses:
        "200":
          description: Successful response
servers:
  - url: https://urn.etica.ai
    description: URN Resolver EticaAI
  - url: http://localhost:8000
    description: localhost:8000
