# SPDX-License-Identifier: Unlicense OR 0BSD

name: "test-any-urn-resolver-server"

on:
  workflow_dispatch:

env:
  TERM: xterm
  ENV_URNRESOLVER: "https://urn.etica.ai"

jobs:
  "main":
    name: "test-any-urn-resolver-server"
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:

      #### Fetch data __________________________________________________________
      - uses: actions/checkout@v3

      #### Tests________________________________________________________________
      - run: URNRESOLVER=https://urn.etica.ai ./scripts/urnresolver-self-test.sh
        continue-on-error: true

      - run: URNRESOLVER="$ENV_URNRESOLVER" ./scripts/urnresolver-self-test.sh
        continue-on-error: true

